### PR TITLE
Removes the initialization of the dirty property from the frontend

### PR DESCRIPTION
**Pull request by hbcarlos**

### CODE REVIEW

**Review by davidbrochart — COMMENTED** [review]
Thanks Carlos.
I see you removed the clearing of the dirty flag, but what about the setting?

**Comment by hbcarlos** [comment]
Good point, no need to have it since we will never modify the attribute from the frontend.

**Comment by davidbrochart** [comment]
Although I can't see where, the dirty flag is still set from the front-end, because when one client changes a document, another one has its dirty flag set.

**Comment by davidbrochart** [comment]
OK so after discussing, it is normal that the dirty flag is "seen" by several clients, because they see the document changing and set their local dirty flag.
Merging! Thanks Carlos.

**Pull request merged**
